version: '3.8'

services:
  web:
    image: php:8.2-apache
    container_name: php-apache-template
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/html
    environment:
      - APACHE_LOG_DIR=/var/log/apache2
    networks:
      - backend

  db:
    image: mysql:8.0
    container_name: mysql-db-template
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: cloudnexus
      MYSQL_USER: testuser
      MYSQL_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend

volumes:
  db_data:

networks:
  backend:

